controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
    game.setGameOverMessage(false, "You left the casino (2/4)")
    game.gameOver(false)
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    game.setGameOverMessage(false, "You left the casino (2/4)")
    game.gameOver(false)
})
info.onCountdownEnd(function () {
    game.setGameOverMessage(true, "You got $1 (3/4)")
    game.gameOver(true)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Projectile, function (sprite, otherSprite) {
    info.changeLifeBy(-1)
    info.changeCountdownBy(10)
    mySprite.setPosition(1, 110)
    Evil_guy.setPosition(136, 16)
})
info.onLifeZero(function () {
    sprites.destroy(mySprite)
    game.setGameOverMessage(false, "You went bankrupt (1/4)")
    game.gameOver(false)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Food, function (sprite, otherSprite) {
    sprites.destroyAllSpritesOfKind(SpriteKind.Food)
    info.changeLifeBy(randint(-1, 1))
    info.changeCountdownBy(randint(-20, 10))
    info.setScore(randint(1, 7500))
})
info.onScore(7500, function () {
    game.setGameOverMessage(true, "Jackpot. You won $5 (4/4)")
    game.gameOver(true)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    info.changeLifeBy(-1)
    sprites.destroy(Evil_guy)
    Evil_guy = sprites.create(assets.image`myImage15`, SpriteKind.Enemy)
    Evil_guy.setPosition(136, 7)
    Evil_guy.follow(mySprite, 45)
    mySprite.setPosition(30, 79)
    info.changeCountdownBy(20)
})
let Heart: Sprite = null
let mySprite: Sprite = null
let Evil_guy: Sprite = null
Evil_guy = sprites.create(assets.image`myImage15`, SpriteKind.Enemy)
Evil_guy.setPosition(137, 7)
mySprite = sprites.create(assets.image`myImage`, SpriteKind.Player)
mySprite.setPosition(3, 109)
info.setLife(3)
scene.setBackgroundColor(9)
controller.moveSprite(mySprite, 100, 100)
mySprite.setStayInScreen(true)
mySprite.sayText("Let's go gambling", 5000, false)
Evil_guy.sayText("STOP STEALING OUR MONEY BY GAMBLING!!!", 5000, false)
Evil_guy.follow(mySprite, 45)
info.startCountdown(90)
game.setGameOverScoringType(game.ScoringType.HighScore)
let Fire_ball = sprites.createProjectileFromSide(assets.image`myImage14`, 50, 25)
Fire_ball.setBounceOnWall(true)
Fire_ball = sprites.createProjectileFromSide(assets.image`myImage14`, 24, 52)
Fire_ball.setBounceOnWall(true)
Fire_ball = sprites.createProjectileFromSide(assets.image`myImage14`, 84, 10)
Fire_ball.setBounceOnWall(true)
game.onUpdateInterval(5000, function () {
    Heart = sprites.create(assets.image`myImage4`, SpriteKind.Food)
})
